// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'






    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQxdL19-7aXJAnSJO0QHzwTZqj5ODRu_c',
    appId: '1:162190627165:web:20fc896d75ba00a86258b4',
    messagingSenderId: '162190627165',
    projectId: 'fila-8005f',
    authDomain: 'fila-8005f.firebaseapp.com',
    storageBucket: 'fila-8005f.firebasestorage.app',
    measurementId: 'G-16FT176GLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_78gk6WBRZ6D4S3tD4PLyy9gGRPh7yc',
    appId: '1:162190627165:android:d9eb93ff9c0c5e6f6258b4',
    messagingSenderId: '162190627165',
    projectId: 'fila-8005f',
    storageBucket: 'fila-8005f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc18PKaQQNOciyf_6K9KJ71cwAnGofEpA',
    appId: '1:162190627165:ios:bea88dc9002c80196258b4',
    messagingSenderId: '162190627165',
    projectId: 'fila-8005f',
    storageBucket: 'fila-8005f.firebasestorage.app',
    iosBundleId: 'com.example.recepcaoPrecheckin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc18PKaQQNOciyf_6K9KJ71cwAnGofEpA',
    appId: '1:162190627165:ios:bea88dc9002c80196258b4',
    messagingSenderId: '162190627165',
    projectId: 'fila-8005f',
    storageBucket: 'fila-8005f.firebasestorage.app',
    iosBundleId: 'com.example.recepcaoPrecheckin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQxdL19-7aXJAnSJO0QHzwTZqj5ODRu_c',
    appId: '1:162190627165:web:cd510ddd7eb474086258b4',
    messagingSenderId: '162190627165',
    projectId: 'fila-8005f',
    authDomain: 'fila-8005f.firebaseapp.com',
    storageBucket: 'fila-8005f.firebasestorage.app',
    measurementId: 'G-DMBJ2YY308',
  );
}
